#!/bin/bash 
# Updating Enlightenment Desktop 
# Tony (August 2014)
# emperor.cu@gmail.com

clear;
#export HTTP_PROXY="http://127.0.0.1:3128"
cd ~/extra-packages/enlightenment/;

#####   Updating Core repositories   #####
echo "Updating Core repositories..." && echo;
sleep 2;

for coredirs in \
    efl \
    evas_generic_loaders \
    emotion_generic_players \
    elementary \
    enligthenment;
do 
    echo "Updating ${coredirs}";
    cd core/${coredirs};
        git pull;
        cd ../../;
    echo;
    sleep 3;
    clear;
done; 

######   Compiling Enlightenment Core   ######
echo && echo "Compiling Core?: [Y/N]" && read Q;

if [ ${Q} == "Y" ] || [ ${Q} == "y" ]; then
    for coredirs in \
        efl \
        evas_generic_loaders \
        emotion_generic_players \
        elementary \
        enlightenment;
    do 
        echo "Compiling ${coredirs}";
        sleep 3;
        cd core/${coredirs};
            sudo make clean;
            sudo ./autogen.sh;
            if [ ${coredirs} == "efl" ]; then
                ./configure \
                    --prefix=/usr/local \
                    --enable-xinput22 \
                    --enable-multisense \
                    --enable-systemd \
                    --enable-image-loader-webp \
                    --enable-harfbuzz \
                    --enable-fb \
                    --disable-tslib \
                    --disable-gstreamer1 \
                    --enable-wayland \
                    --enable-xine \
                    --enable-drm \
                    --enable-i-really-know-what-i-am-doing-and-that-this-will-probably-break-things-and-i-will-fix-them-myself-and-send-patches-aba;
            else
                ./configure --prefix=/usr/local;
            fi;
            sudo make; 
            sudo make install; 
            sudo ldconfig; 
            cd ../../;
    done;
    echo "Exiting of core..." && echo && sleep 3;
fi;

#####   Bindings repositories   #####
clear;
echo "Updating Bindings repositories..." && echo;
sleep 2;
cd ~/extra-packages/enlightenment/;

for bindingsdir in \
    python-efl \
    python-e_dbus \
    python-ecore \
    python-edje \
    python-elementary \
    python-emotion \
    python-ethumb \
    python-evas;
do 
    echo "Updating ${bindingsdir}";
    cd bindings/${bindingsdir};
        git pull; 
        cd ../../;
    sleep 3;
    clear;
done;
echo "Exiting of Bindings..." && echo && sleep 2;

#####   Compiling Bindings   #####
echo "Compiling Bindings?: [Y/N]" && read Q;

export PYTHONPATH=/usr/include/python2.7/:/usr/lib/python2.7/dist-packages/;
if [ ${Q} == "Y" ] || [ ${Q} == "y" ]; then
    # python-e_dbus , TODO: NOT INCLUDE FOR NOW
    for bindingsdir in \
        python-efl \
        python-evas \
        python-ecore \
        python-edje \
        python-elementary \
        python-emotion \
        python-ethumb;
    do 
        echo Compiling ${bindingsdir};
        sleep 1;
        cd bindings/${bindingsdir};
            if [ ${bindingsdir} == "python-efl" ]; then
                sudo python setup.py install;
            else
                sudo make clean;
                ./autogen.sh;
                ./configure --prefix=/usr/local;
                make;
                sudo make install;
                sudo ldconfig;
                cd ../../;
            fi;
    done;
    echo "Exiting of bindings..." && echo && sleep 3;
fi;

#####   Updating Other stuff   #####
clear;
echo "Updating Modules repositories..." && echo;
sleep 2;
cd ~/extra-packages/enlightenment/;

for modulesdir in \
    alarm \
    comp-scale \
    cpu diskio \
    eenvader.fractal \
    elev8 \
    elfe \
    empris \
    engage \
    everything-places \
    everything-websearch \
    eweather \
    forecasts \
    mail \
    moon \
    mpdule \
    net \
    news \
    penguins \
    photo \
    places \
    tclock;
do
    echo "Updating ${modulesdir}";
    cd modules/${modulesdir}
        git pull; 
        cd ../../;
    sleep 3;
    clear;
done; 
echo "Exiting of Modules..." && echo && sleep 2;

#####   Compiling Enlightenment Modules   #####
echo "Compiling Modules?: [Y/N]" && read Q;

if [ ${Q} == "Y" ] || [ ${Q} == "y" ]; then
    echo "Compiling Modules";
    sleep 1;
    # TODO: Problems in followings modules
    #comp-scale \
    #elev8 \
    #elfe \
    #empris \
    #engage \
    #mail \
    #moon \
    ##everything-websearch \
    ##mpdule \
    #news \
    #photo \
    for modulesdir in \
        alarm \
        cpu \
        diskio \
        eenvader.fractal \
        everything-places \
        forecasts \
        net \
        penguins \
        places \
        tclock;
    do 
        cd modules/${modulesdir}; 
            sudo make clean;
            ./autogen.sh; 
            ./configure --prefix=/usr/local; 
            make; 
            sudo make install; 
            sudo ldconfig; 
            cd ../../;
    done; 
else
    echo "Exiting of Modules" && echo && sleep 3;
fi


#####   Updating extra misc   #####
clear;
echo "Updating the rest of extra misc..."
sleep 2;
cd ~/extra-packages/enlightenment/;

for gamesdir in \
    e_cho \
    econcentration \
    efbb \
    elemines \
    eskiss \
    etrophy;
do 
    echo "Updating ${gamesdir}";
    cd games/${gamesdir};
        git pull;
        cd ../../;
    sleep 1;
    clear;
done;

for themesdir in \
    23oz \
    b_and_w \
    blingbling \
    darkness \
    detour-elm \
    detourious \
    efenniht \
    ewl_b_and_w \
    klok;
do
    echo "Updating ${themesdir}";
    cd themes/${themesdir};
        git pull;
        cd ../../;
    sleep 1;
    clear;
done;

for toolsdir in \
    clouseau \
    edje_list \
    edje_smart_thumb \
    enventor \
    exactness-edje-data \
    exactness-elm-data \
    exactness \
    formatting \
    geneet;
do
    echo "Updating ${toolsdir}";
    cd tools/${toolsdir};
        git pull;
        cd ../../;
    sleep 1;
    clear;
done;

for discomfitordirs in \
    efx \
    erssd \
    s2 \
    emote;
do
    echo "Updating ${discomfitordirs}";
    cd discomfitor/${discomfitordirs};
        git pull;
        cd ../../;
    sleep 1;
    clear;
done;

# APPS WORKING STABLES ON ENLIGHTENMENT
# eterm: for me was change for terminology (MORE COOLER TERMINAL) ;-)

cd ~/extra-packages/enlightenment/;

for apps_stable in \
    lightmediascanner \
    enjoy \
    ecrire \
    emprint \
    ephoto \
    epour \
    equate \
    espionage \
    terminology;
do
    echo "Updating ${apps_stable}";
    cd applications/${apps_stable};
        git pull;
        cd ../../;
    slee 1;
    clear;
done;

# Compiling Enlightenment Applications
echo "Compiling Applications?: [Y/N]" && read Q

cd ~/extra-packages/enlightenment/;
if [ ${Q} == "Y" ] || [ ${Q} == "y" ]; then
    cd applications/econnman
    sudo make clean;
    sudo ./configure;
    sudo make;
    sudo make install;
    cd ../../;
    for appsdir in \
        epour \
        epymc;
    do
        echo "Compiling ${appsdir}";
        sleep 1;
        cd applications/${appsdir}
            sudo python setup.py install;
            sleep 3;
            cd ../../;
        clear;
    done;

    for appsdir in \
        egitu \
        ephoto \
        enventor \
        ecrire \
        equate \
        espionage \
        rage;
    do 
        echo "Compiling ${appsdir}";
        sleep 1;
        cd applications/${appsdir}; 
            sudo make clean;
            ./autogen.sh;
            ./configure --prefix=/usr/local;
            make;
            sudo make install;
            sudo ldconfig;
            cd ../../;
        clear;
    done;
    echo "Exiting of Applications" && echo && sleep 3;
fi;

cd ~/extra-packages/enlightenment/;

# OTHERS APPS FROM DEVELOPERS OF ENLIGHTENMENT
for developers in \
    kiwi/egraph \
    kiwi/elife \
    kuuko/apathy \
    kuuko/valosoitin \
    yakov/egui \
    yakov/eo_bindings;
do
    echo "Updating ${developers}";
    cd ${developers};
        git pull;
        cd ../../;
    sleep 1;
    clear;
done;

# Compiling Enlightenment developers Applications
echo "Compiling Applications from developers?: [Y/N]" && read Q;

if [ ${Q} == "Y" ] || [ ${Q} == "y" ]; then
    for devels_apps in \
        kiwi/egraph \
        kiwi/elife \
        kuuko/apathy \
        kuuko/valosoitin \
        yakov/egui \
        yakov/eo_bindings;
    do
        echo "Compiling ${appsdir}";
        sleep 1;
        cd ${devels_apps};
            sudo install clean;
            ./autogen.sh;
            ./configure --prefix=/usr/local;
            make;
            sudo make install;
            sudo ldconfig;
            cd ../../;
    done;
    echo "Exiting from developers Applications" && echo && sleep 3;
fi;
echo;
echo "Done!";
sleep 1;
clear;
exit 0;
